/* tslint:disable */
/* eslint-disable */
/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CertificatesApi - axios parameter creator
 * @export
 */
export const CertificatesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Webhook CA Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWebhookCa: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/certificates/webhooks/ca`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/certificates/webhooks/ca',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Download-CA-Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCaCertificate: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/certificates/external/ca`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/certificates/external/ca',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Download Webhook CA Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadWebhookCaCertificate: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/certificates/webhooks/ca`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/certificates/webhooks/ca',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload-Certificate
         * @param {Uint8Array | File | buffer.File} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadExternalCertificate: async (body?: Uint8Array | File | buffer.File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/certificates/external`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'text/plain';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: body,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/certificates/external',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload Webhook CA Certificate
         * @param {Uint8Array | File | buffer.File} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadWebhookCaCertificate: async (body?: Uint8Array | File | buffer.File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/certificates/webhooks/ca`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'text/plain';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: body,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/certificates/webhooks/ca',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CertificatesApi - functional programming interface
 * @export
 */
export const CertificatesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CertificatesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete Webhook CA Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWebhookCa(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWebhookCa(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Download-CA-Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadCaCertificate(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Uint8Array | File | buffer.File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadCaCertificate(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Download Webhook CA Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadWebhookCaCertificate(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Uint8Array | File | buffer.File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadWebhookCaCertificate(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload-Certificate
         * @param {CertificatesApiUploadExternalCertificateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadExternalCertificate(requestParameters: CertificatesApiUploadExternalCertificateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const body: Uint8Array | File | buffer.File = requestParameters;
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadExternalCertificate(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Upload Webhook CA Certificate
         * @param {CertificatesApiUploadWebhookCaCertificateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadWebhookCaCertificate(requestParameters: CertificatesApiUploadWebhookCaCertificateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const body: Uint8Array | File | buffer.File = requestParameters;
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadWebhookCaCertificate(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CertificatesApi - factory interface
 * @export
 */
export const CertificatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CertificatesApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete Webhook CA Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWebhookCa(options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteWebhookCa(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Download-CA-Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadCaCertificate(options?: AxiosRequestConfig): AxiosPromise<Uint8Array | File | buffer.File> {
            return localVarFp.downloadCaCertificate(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Download Webhook CA Certificate
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadWebhookCaCertificate(options?: AxiosRequestConfig): AxiosPromise<Uint8Array | File | buffer.File> {
            return localVarFp.downloadWebhookCaCertificate(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload-Certificate
         * @param {CertificatesApiUploadExternalCertificateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadExternalCertificate(requestParameters: CertificatesApiUploadExternalCertificateRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.uploadExternalCertificate(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload Webhook CA Certificate
         * @param {CertificatesApiUploadWebhookCaCertificateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadWebhookCaCertificate(requestParameters: CertificatesApiUploadWebhookCaCertificateRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.uploadWebhookCaCertificate(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for uploadExternalCertificate operation in CertificatesApi.
 * @export
 * @interface CertificatesApiUploadExternalCertificateRequest
 */
export type CertificatesApiUploadExternalCertificateRequest = Uint8Array | File | buffer.File

/**
 * Request parameters for uploadWebhookCaCertificate operation in CertificatesApi.
 * @export
 * @interface CertificatesApiUploadWebhookCaCertificateRequest
 */
export type CertificatesApiUploadWebhookCaCertificateRequest = Uint8Array | File | buffer.File

/**
 * CertificatesApiGenerated - object-oriented interface
 * @export
 * @class CertificatesApiGenerated
 * @extends {BaseAPI}
 */
export class CertificatesApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Delete Webhook CA Certificate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiGenerated
     */
    public deleteWebhookCa(options?: AxiosRequestConfig) {
        return CertificatesApiFp(this.configuration).deleteWebhookCa(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Download-CA-Certificate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiGenerated
     */
    public downloadCaCertificate(options?: AxiosRequestConfig) {
        return CertificatesApiFp(this.configuration).downloadCaCertificate(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Download Webhook CA Certificate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiGenerated
     */
    public downloadWebhookCaCertificate(options?: AxiosRequestConfig) {
        return CertificatesApiFp(this.configuration).downloadWebhookCaCertificate(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload-Certificate
     * @param {CertificatesApiUploadExternalCertificateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiGenerated
     */
    public uploadExternalCertificate(requestParameters: CertificatesApiUploadExternalCertificateRequest, options?: AxiosRequestConfig) {
        return CertificatesApiFp(this.configuration).uploadExternalCertificate(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload Webhook CA Certificate
     * @param {CertificatesApiUploadWebhookCaCertificateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CertificatesApiGenerated
     */
    public uploadWebhookCaCertificate(requestParameters: CertificatesApiUploadWebhookCaCertificateRequest, options?: AxiosRequestConfig) {
        return CertificatesApiFp(this.configuration).uploadWebhookCaCertificate(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
