/* tslint:disable */
/* eslint-disable */
/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetProfileAboutResponse } from '../models';
// @ts-ignore
import { GetProfilePhotoResponse } from '../models';
// @ts-ignore
import { ProfileAbout } from '../models';
// @ts-ignore
import { ProfileUpdatePhotoRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ProfileApi - axios parameter creator
 * @export
 */
export const ProfileApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get-Profile-About
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAbout: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/settings/profile/about`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/settings/profile/about',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get-Profile-Photo
         * @param {string} [format] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPhoto: async (format?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/settings/profile/photo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/settings/profile/photo',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete-Profile-Photo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removePhoto: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/settings/profile/photo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/settings/profile/photo',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update-Profile-About
         * @param {ProfileAbout} profileAbout 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAbout: async (profileAbout: ProfileAbout, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileAbout' is not null or undefined
            assertParamExists('updateAbout', 'profileAbout', profileAbout)
            const localVarPath = `/settings/profile/about`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: profileAbout,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/settings/profile/about',
                httpMethod: 'PATCH'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(profileAbout, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update-Profile-Photo
         * @param {Uint8Array | File | buffer.File} file 
         * @param {ProfileUpdatePhotoRequest} [profileUpdatePhotoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePhoto: async (file: Uint8Array | File | buffer.File, profileUpdatePhotoRequest?: ProfileUpdatePhotoRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('updatePhoto', 'file', file)
            const localVarPath = `/settings/profile/photo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            const addFormParam = async (name: string, data: any, isBinary: boolean, isPrimitiveType: boolean) => {
                if (isBinary) {
                    if (data instanceof Uint8Array) {
                        // Handle Buffer data
                        const filetype = await fromBuffer(data)
                        const filename = filetype === undefined ? name : `${name}.${filetype.ext}`
                        localVarFormParams.append(name, data as any, filename);
                    } else if ("name" in data) {
                        // File instances in browsers and Node.js have the
                        // "name" property "Duck typing" files to handle browser
                        // File class or Node.js File class
                        // Web: https://developer.mozilla.org/en-US/docs/Web/API/File
                        // Node.js: https://nodejs.org/api/buffer.html#new-bufferfilesources-filename-options
                        if (isBrowser()) {
                            // FormData in browser can accept File/Blob directly
                            localVarFormParams.append(name, data, data.name);
                        } else {
                            // FormData in Node.js can only accept raw Buffer so convert before passing
                            const bytes = await data.arrayBuffer()
                            const buffer = Buffer.from(bytes)
                            localVarFormParams.append(name, buffer, data.name);
                        }
                    }
                } else {
                    if (isPrimitiveType) {
                        /**
                         * FormData can only accept string or Blob so we need to convert
                         * non-string primitives to string. We also need to convert
                         */
                        if (typeof data === "object") {
                          localVarFormParams.append(name, JSON.stringify(data));
                        } else {
                          localVarFormParams.append(name, data);
                        }
                    } else {
                        if (isBrowser()) {
                            localVarFormParams.append(name, new Blob([JSON.stringify(data)], { type: "application/json" }))
                        } else {
                            localVarFormParams.append(name, JSON.stringify(data), { type: "application/json", filename: "data.json" });
                        }
                    }
                }
            }
            if (!isBrowser()) Object.assign(localVarHeaderParameter, localVarFormParams.getHeaders());

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (file !== undefined) {
                await addFormParam('File', file, true, true)
            }
    
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;
            requestBeforeHook({
                requestBody: profileUpdatePhotoRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/settings/profile/photo',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProfileApi - functional programming interface
 * @export
 */
export const ProfileApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProfileApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get-Profile-About
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAbout(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetProfileAboutResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAbout(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get-Profile-Photo
         * @param {ProfileApiGetPhotoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPhoto(requestParameters: ProfileApiGetPhotoRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetProfilePhotoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPhoto(requestParameters.format, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete-Profile-Photo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removePhoto(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removePhoto(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update-Profile-About
         * @param {ProfileApiUpdateAboutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAbout(requestParameters: ProfileApiUpdateAboutRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const profileAbout: ProfileAbout = {
                text: requestParameters.text
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAbout(profileAbout, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update-Profile-Photo
         * @param {ProfileApiUpdatePhotoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePhoto(requestParameters: ProfileApiUpdatePhotoRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const profileUpdatePhotoRequest: ProfileUpdatePhotoRequest = {
                File: requestParameters.File
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePhoto(requestParameters.file, profileUpdatePhotoRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProfileApi - factory interface
 * @export
 */
export const ProfileApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProfileApiFp(configuration)
    return {
        /**
         * 
         * @summary Get-Profile-About
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAbout(options?: AxiosRequestConfig): AxiosPromise<GetProfileAboutResponse> {
            return localVarFp.getAbout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get-Profile-Photo
         * @param {ProfileApiGetPhotoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPhoto(requestParameters: ProfileApiGetPhotoRequest = {}, options?: AxiosRequestConfig): AxiosPromise<GetProfilePhotoResponse> {
            return localVarFp.getPhoto(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete-Profile-Photo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removePhoto(options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removePhoto(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update-Profile-About
         * @param {ProfileApiUpdateAboutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAbout(requestParameters: ProfileApiUpdateAboutRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateAbout(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update-Profile-Photo
         * @param {ProfileApiUpdatePhotoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePhoto(requestParameters: ProfileApiUpdatePhotoRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updatePhoto(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getPhoto operation in ProfileApi.
 * @export
 * @interface ProfileApiGetPhotoRequest
 */
export type ProfileApiGetPhotoRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof ProfileApiGetPhoto
    */
    readonly format?: string
    
}

/**
 * Request parameters for updateAbout operation in ProfileApi.
 * @export
 * @interface ProfileApiUpdateAboutRequest
 */
export type ProfileApiUpdateAboutRequest = {
    
} & ProfileAbout

/**
 * Request parameters for updatePhoto operation in ProfileApi.
 * @export
 * @interface ProfileApiUpdatePhotoRequest
 */
export type ProfileApiUpdatePhotoRequest = {
    
    /**
    * 
    * @type {Uint8Array | File | buffer.File}
    * @memberof ProfileApiUpdatePhoto
    */
    readonly file: Uint8Array | File | buffer.File
    
} & ProfileUpdatePhotoRequest

/**
 * ProfileApiGenerated - object-oriented interface
 * @export
 * @class ProfileApiGenerated
 * @extends {BaseAPI}
 */
export class ProfileApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Get-Profile-About
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApiGenerated
     */
    public getAbout(options?: AxiosRequestConfig) {
        return ProfileApiFp(this.configuration).getAbout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get-Profile-Photo
     * @param {ProfileApiGetPhotoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApiGenerated
     */
    public getPhoto(requestParameters: ProfileApiGetPhotoRequest = {}, options?: AxiosRequestConfig) {
        return ProfileApiFp(this.configuration).getPhoto(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete-Profile-Photo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApiGenerated
     */
    public removePhoto(options?: AxiosRequestConfig) {
        return ProfileApiFp(this.configuration).removePhoto(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update-Profile-About
     * @param {ProfileApiUpdateAboutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApiGenerated
     */
    public updateAbout(requestParameters: ProfileApiUpdateAboutRequest, options?: AxiosRequestConfig) {
        return ProfileApiFp(this.configuration).updateAbout(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update-Profile-Photo
     * @param {ProfileApiUpdatePhotoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileApiGenerated
     */
    public updatePhoto(requestParameters: ProfileApiUpdatePhotoRequest, options?: AxiosRequestConfig) {
        return ProfileApiFp(this.configuration).updatePhoto(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
