/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Media } from './media';
import { Webhooks } from './webhooks';

/**
 * 
 * @export
 * @interface ApplicationSettings
 */
export interface ApplicationSettings {
    /**
     * Backoff delay for a failed callback in milliseconds This setting is used to configure the amount of time the backoff delays before retrying a failed callback. The backoff delay increases linearly by this value each time a callback fails to get a HTTPS 200 OK response. The backoff delay is capped by the max_callback_backoff_delay_ms setting.
     * @type {string}
     * @memberof ApplicationSettings
     */
    'callback_backoff_delay_ms'?: string;
    /**
     * Stores callbacks on disk until they are successfully acknowledged by the Webhook or not. Restart required.
     * @type {boolean}
     * @memberof ApplicationSettings
     */
    'callback_persist'?: boolean;
    /**
     * Multiconnect: Interval of the Master node monitoring of Coreapp nodes in seconds
     * @type {number}
     * @memberof ApplicationSettings
     */
    'heartbeat_interval'?: number;
    /**
     * Maximum delay for a failed callback in milliseconds
     * @type {string}
     * @memberof ApplicationSettings
     */
    'max_callback_backoff_delay_ms'?: string;
    /**
     * 
     * @type {Media}
     * @memberof ApplicationSettings
     */
    'media'?: Media;
    /**
     * Set to valid WhatsApp Group with users who wish to see alerts for critical errors and messages.
     * @type {string}
     * @memberof ApplicationSettings
     */
    'on_call_pager'?: string;
    /**
     * When true, removes messages from the local database after they are delivered to or read by the recipient. When false, saves all messages on local storage until they are explicitly deleted. When messages are sent, they are stored in a local database. This database is used as the application\'s history. Since the business keeps its own history, you can specify whether you want message pass_through or not. Restart required.
     * @type {boolean}
     * @memberof ApplicationSettings
     */
    'pass_through'?: boolean;
    /**
     * Receive a notification that a message is sent to server. When true, you will receive a message indicating that a message has been sent. If false (default), you will not receive notification.
     * @type {boolean}
     * @memberof ApplicationSettings
     */
    'sent_status'?: boolean;
    /**
     * Multiconnect: Maximum amount of seconds a Master node waits for a Coreapp node to respond to a heartbeat before considering it unhealthy and starting the failover process.
     * @type {number}
     * @memberof ApplicationSettings
     */
    'unhealthy_interval'?: number;
    /**
     * 
     * @type {Webhooks}
     * @memberof ApplicationSettings
     */
    'webhooks'?: Webhooks;
}

