/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Provider } from './provider';

/**
 * 
 * @export
 * @interface AudioByProvider
 */
export interface AudioByProvider {
    /**
     * 
     * @type {string}
     * @memberof AudioByProvider
     */
    'link': string;
    /**
     * 
     * @type {Provider}
     * @memberof AudioByProvider
     */
    'provider': Provider;
}

