/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AudioById } from './audio-by-id';
import { AudioByProvider } from './audio-by-provider';
import { Provider } from './provider';

/**
 * @type Audio
 * The media object containing audio
 * @export
 */
export type Audio = AudioById | AudioByProvider;


