/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BackupSettings } from './backup-settings';

/**
 * Save the data value as that will be used along with your password to restore the information.
 * @export
 * @interface BackupSettingsResponse
 */
export interface BackupSettingsResponse {
    /**
     * 
     * @type {BackupSettings}
     * @memberof BackupSettingsResponse
     */
    'settings'?: BackupSettings;
}

