/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BackupSettings
 */
export interface BackupSettings {
    /**
     * The data that has been backed up, encrypted for security.
     * @type {string}
     * @memberof BackupSettings
     */
    'data'?: string;
}

