/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BusinessProfile
 */
export interface BusinessProfile {
    /**
     * Description of the business Maximum of 256 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    'description': string;
    /**
     * Address of the business Maximum of 256 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    'address': string;
    /**
     * Email address to contact the business Maximum of 128 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    'email': string;
    /**
     * Industry of the business Maximum of 128 characters
     * @type {string}
     * @memberof BusinessProfile
     */
    'vertical': string;
    /**
     * URLs associated with business (e.g., website, Facebook page, Instagram) Maximum of 2 websites with a maximum of 256 characters each
     * @type {Array<string>}
     * @memberof BusinessProfile
     */
    'websites': Array<string>;
}

