/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessSettingsBusiness } from './business-settings-business';

/**
 * 
 * @export
 * @interface BusinessSettings
 */
export interface BusinessSettings {
    /**
     * 
     * @type {BusinessSettingsBusiness}
     * @memberof BusinessSettings
     */
    'business'?: BusinessSettingsBusiness;
}

