/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckContact } from './check-contact';

/**
 * 
 * @export
 * @interface CheckContactResponseAllOf
 */
export interface CheckContactResponseAllOf {
    /**
     * 
     * @type {Array<CheckContact>}
     * @memberof CheckContactResponseAllOf
     */
    'contacts'?: Array<CheckContact>;
}

