/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckContact
 */
export interface CheckContact {
    /**
     * The value you sent in the contacts field of the JSON request.
     * @type {string}
     * @memberof CheckContact
     */
    'input'?: string;
    /**
     * Status of the user.
     * @type {string}
     * @memberof CheckContact
     */
    'status'?: CheckContactStatusEnum;
    /**
     * WhatsApp user identifier that can be used in other API calls. Only returned if the status is valid.
     * @type {string}
     * @memberof CheckContact
     */
    'wa_id'?: string;
}

type CheckContactStatusEnum = 'processing' | 'valid' | 'invalid'


