/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GatewayNodeStatus } from './gateway-node-status';
import { GatewayStatus } from './gateway-status';

/**
 * @type CheckHealthResponseHealth
 * @export
 */
export type CheckHealthResponseHealth = GatewayStatus | { [key: string]: GatewayNodeStatus; };


