/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Basic } from './basic';

/**
 * 
 * @export
 * @interface ConfigBasic
 */
export interface ConfigBasic {
    /**
     * 
     * @type {Basic}
     * @memberof ConfigBasic
     */
    'basic'?: Basic;
}

