/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Basic } from './basic';
import { ConfigBasic } from './config-basic';
import { ConfigBearer } from './config-bearer';

/**
 * @type Config
 * @export
 */
export type Config = ConfigBasic | ConfigBearer;


