/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Email } from './email';
import { Name } from './name';
import { Org } from './org';
import { Phone } from './phone';
import { Url } from './url';

/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * Full contact address(es)
     * @type {Array<Address>}
     * @memberof Contact
     */
    'addresses'?: Array<Address>;
    /**
     * YYYY-MM-DD formatted string
     * @type {string}
     * @memberof Contact
     */
    'birthday'?: string;
    /**
     * Contact email address(es)
     * @type {Array<Email>}
     * @memberof Contact
     */
    'emails'?: Array<Email>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Contact
     */
    'ims'?: Array<string>;
    /**
     * 
     * @type {Name}
     * @memberof Contact
     */
    'name'?: Name;
    /**
     * 
     * @type {Org}
     * @memberof Contact
     */
    'org'?: Org;
    /**
     * Contact phone number(s)
     * @type {Array<Phone>}
     * @memberof Contact
     */
    'phones'?: Array<Phone>;
    /**
     * Contact URL(s)
     * @type {Array<Url>}
     * @memberof Contact
     */
    'urls'?: Array<Url>;
}

