/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateUserRequestBody
 */
export interface CreateUserRequestBody {
    /**
     * username
     * @type {string}
     * @memberof CreateUserRequestBody
     */
    'password': string;
    /**
     * password
     * @type {string}
     * @memberof CreateUserRequestBody
     */
    'username': string;
}

