/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DateTimeComponent } from './date-time-component';
import { DateTimeUnixEpoch } from './date-time-unix-epoch';

/**
 * The Whatsapp Business API Client will attempt to format the date/time based on a specified localization.
 * @export
 * @interface DateTimeObject
 */
export interface DateTimeObject {
    /**
     * 
     * @type {DateTimeComponent}
     * @memberof DateTimeObject
     */
    'component'?: DateTimeComponent;
    /**
     * 
     * @type {DateTimeUnixEpoch}
     * @memberof DateTimeObject
     */
    'unix_epoch'?: DateTimeUnixEpoch;
}

