/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Date/time by Unix epoch
 * @export
 * @interface DateTimeUnixEpoch
 */
export interface DateTimeUnixEpoch {
    /**
     * Epoch timestamp in seconds
     * @type {number}
     * @memberof DateTimeUnixEpoch
     */
    'timestamp'?: number;
}

