/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DetailedUserResponseItem } from './detailed-user-response-item';

/**
 * 
 * @export
 * @interface DetailedUserResponseAllOf
 */
export interface DetailedUserResponseAllOf {
    /**
     * 
     * @type {Array<DetailedUserResponseItem>}
     * @memberof DetailedUserResponseAllOf
     */
    'users'?: Array<DetailedUserResponseItem>;
}

