/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentById } from './document-by-id';
import { DocumentByProvider } from './document-by-provider';
import { Provider } from './provider';

/**
 * @type Document
 * The media object containing a document
 * @export
 */
export type Document = DocumentById | DocumentByProvider;


