/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GatewayNodeStatus
 */
export interface GatewayNodeStatus {
    /**
     * 
     * @type {string}
     * @memberof GatewayNodeStatus
     */
    'gateway_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayNodeStatus
     */
    'role'?: GatewayNodeStatusRoleEnum;
}

type GatewayNodeStatusRoleEnum = 'primary_master' | 'secondary_master' | 'coreapp'


