/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GetMediaProvidersResponseAllOf } from './get-media-providers-response-all-of';
import { MediaProviderSettings } from './media-provider-settings';
import { Meta } from './meta';
import { Response } from './response';

/**
 * @type GetMediaProvidersResponse
 * 
 * @export
 */
export type GetMediaProvidersResponse = GetMediaProvidersResponseAllOf & Response;


