/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessSettings } from './business-settings';
import { GetBusinessProfileResponseAllOf } from './get-business-profile-response-all-of';
import { Meta } from './meta';
import { Response } from './response';

/**
 * @type GetBusinessProfileResponse
 * 
 * @export
 */
export type GetBusinessProfileResponse = GetBusinessProfileResponseAllOf & Response;


