/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Group
 */
export interface Group {
    /**
     * timestamp
     * @type {number}
     * @memberof Group
     */
    'creation_time'?: number;
    /**
     * 
     * @type {string}
     * @memberof Group
     */
    'id'?: string;
}

