/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupInvite } from './group-invite';

/**
 * 
 * @export
 * @interface GroupInviteResponseAllOf
 */
export interface GroupInviteResponseAllOf {
    /**
     * 
     * @type {Array<GroupInvite>}
     * @memberof GroupInviteResponseAllOf
     */
    'groups'?: Array<GroupInvite>;
}

