/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Group } from './group';
import { GroupsResponseAllOf } from './groups-response-all-of';
import { Meta } from './meta';
import { Response } from './response';

/**
 * @type GroupsResponse
 * 
 * @export
 */
export type GroupsResponse = GroupsResponseAllOf & Response;


