/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupInvite } from './group-invite';
import { GroupInviteResponseAllOf } from './group-invite-response-all-of';
import { Meta } from './meta';
import { Response } from './response';

/**
 * @type GroupInviteResponse
 * 
 * @export
 */
export type GroupInviteResponse = GroupInviteResponseAllOf & Response;


