/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Group } from './group';

/**
 * 
 * @export
 * @interface GroupsResponseAllOf
 */
export interface GroupsResponseAllOf {
    /**
     * 
     * @type {Array<Group>}
     * @memberof GroupsResponseAllOf
     */
    'groups'?: Array<Group>;
}

