/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GroupAdminRequestBody
 */
export interface GroupAdminRequestBody {
    /**
     * The WhatsApp IDs of the people to be added or removed as group admins
     * @type {Array<string>}
     * @memberof GroupAdminRequestBody
     */
    'wa_ids': Array<string>;
}

