/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupInfo } from './group-info';
import { GroupResponseAllOf } from './group-response-all-of';
import { Meta } from './meta';
import { Response } from './response';

/**
 * @type GroupResponse
 * 
 * @export
 */
export type GroupResponse = GroupResponseAllOf & Response;


