/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ImageById } from './image-by-id';
import { ImageByProvider } from './image-by-provider';
import { Provider } from './provider';

/**
 * @type Image
 * The media object containing an image
 * @export
 */
export type Image = ImageById | ImageByProvider;


