/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * Address of the location. Only displayed if name is present.
     * @type {string}
     * @memberof Location
     */
    'address': string;
    /**
     * Latitude of the location
     * @type {string}
     * @memberof Location
     */
    'latitude': string;
    /**
     * Longitude of the location
     * @type {string}
     * @memberof Location
     */
    'longitude': string;
    /**
     * Name of the location
     * @type {string}
     * @memberof Location
     */
    'name': string;
}

