/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Currency } from './currency';
import { DateTimeObject } from './date-time-object';

/**
 * 
 * @export
 * @interface LocalizableParam
 */
export interface LocalizableParam {
    /**
     * 
     * @type {Currency}
     * @memberof LocalizableParam
     */
    'currency'?: Currency;
    /**
     * 
     * @type {DateTimeObject}
     * @memberof LocalizableParam
     */
    'date_time'?: DateTimeObject;
    /**
     * Default text if localization fails
     * @type {string}
     * @memberof LocalizableParam
     */
    'default': string;
}

