/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LoginAdminRequestBody
 */
export interface LoginAdminRequestBody {
    /**
     * 
     * @type {string}
     * @memberof LoginAdminRequestBody
     */
    'new_password': string;
}

