/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Media
 */
export interface Media {
    /**
     * An array specifying which types of media to automatically download.
     * @type {Array<string>}
     * @memberof Media
     */
    'auto_download': Array<MediaAutoDownloadEnum>;
}

type MediaAutoDownloadEnum = 'audio' | 'document' | 'voice' | 'video' | 'image.'


