/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MediaProviderSettingsApplication } from './media-provider-settings-application';

/**
 * 
 * @export
 * @interface MediaProviderSettings
 */
export interface MediaProviderSettings {
    /**
     * 
     * @type {MediaProviderSettingsApplication}
     * @memberof MediaProviderSettings
     */
    'application'?: MediaProviderSettingsApplication;
}

