/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Config } from './config';

/**
 * 
 * @export
 * @interface MediaProvider
 */
export interface MediaProvider {
    /**
     * 
     * @type {Config}
     * @memberof MediaProvider
     */
    'config'?: Config;
    /**
     * The name for the provider
     * @type {string}
     * @memberof MediaProvider
     */
    'name'?: string;
    /**
     * The type of provider
     * @type {string}
     * @memberof MediaProvider
     */
    'type'?: string;
}

