/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MediaProvider } from './media-provider';

/**
 * 
 * @export
 * @interface MediaProviderSettingsApplicationMedia
 */
export interface MediaProviderSettingsApplicationMedia {
    /**
     * 
     * @type {Array<MediaProvider>}
     * @memberof MediaProviderSettingsApplicationMedia
     */
    'providers'?: Array<MediaProvider>;
}

