/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessageContext
 */
export interface MessageContext {
    /**
     * Sender Whatsapp id of context-message
     * @type {string}
     * @memberof MessageContext
     */
    'from'?: string;
    /**
     * GroupId of context message
     * @type {string}
     * @memberof MessageContext
     */
    'group_id'?: string;
    /**
     * message id
     * @type {string}
     * @memberof MessageContext
     */
    'id'?: string;
    /**
     * Whats app ids
     * @type {Array<string>}
     * @memberof MessageContext
     */
    'mentions'?: Array<string>;
}

