/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * type of the message
 * @export
 * @enum {string}
 */
export type MessageType = 'audio' | 'contacts' | 'document' | 'hsm' | 'image' | 'location' | 'text' | 'video' | 'voice' | 'unknown'

