/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Message } from './message';

/**
 * 
 * @export
 * @interface MessageResponseAllOf
 */
export interface MessageResponseAllOf {
    /**
     * 
     * @type {Array<Message>}
     * @memberof MessageResponseAllOf
     */
    'messages'?: Array<Message>;
}

