/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Contains generic information such as WhatsApp Business API Client version.
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof Meta
     */
    'api_status'?: MetaApiStatusEnum;
}

type MetaApiStatusEnum = 'deprecated' | 'experimental' | 'stable'


