/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * error title
     * @type {string}
     * @memberof ModelError
     */
    'title'?: string;
    /**
     * See the https://developers.facebook.com/docs/whatsapp/api/errors for more information.
     * @type {number}
     * @memberof ModelError
     */
    'code'?: number;
    /**
     * error detail
     * @type {string}
     * @memberof ModelError
     */
    'details'?: string;
    /**
     * location for error detail
     * @type {string}
     * @memberof ModelError
     */
    'href'?: string;
}

