/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Full contact name
 * @export
 * @interface Name
 */
export interface Name {
    /**
     * First name
     * @type {string}
     * @memberof Name
     */
    'first_name'?: string;
    /**
     * Full name as it normally appears
     * @type {string}
     * @memberof Name
     */
    'formatted_name': string;
    /**
     * Last name
     * @type {string}
     * @memberof Name
     */
    'last_name'?: string;
    /**
     * Name preffix
     * @type {string}
     * @memberof Name
     */
    'prefix'?: string;
    /**
     * Name suffix
     * @type {string}
     * @memberof Name
     */
    'suffix'?: string;
}

