/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Contact organization information
 * @export
 * @interface Org
 */
export interface Org {
    /**
     * Contact\'s business title
     * @type {string}
     * @memberof Org
     */
    'title'?: string;
    /**
     * Name of the contact\'s company
     * @type {string}
     * @memberof Org
     */
    'company': string;
    /**
     * Name of the contact\'s department
     * @type {string}
     * @memberof Org
     */
    'department'?: string;
}

