/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProfileAboutSettingsProfile } from './profile-about-settings-profile';

/**
 * 
 * @export
 * @interface ProfileAboutSettings
 */
export interface ProfileAboutSettings {
    /**
     * 
     * @type {ProfileAboutSettingsProfile}
     * @memberof ProfileAboutSettings
     */
    'profile'?: ProfileAboutSettingsProfile;
}

