/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProfileAbout } from './profile-about';

/**
 * 
 * @export
 * @interface ProfileAboutSettingsProfile
 */
export interface ProfileAboutSettingsProfile {
    /**
     * 
     * @type {ProfileAbout}
     * @memberof ProfileAboutSettingsProfile
     */
    'about'?: ProfileAbout;
}

