/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProfileUpdatePhotoRequest
 */
export interface ProfileUpdatePhotoRequest {
    /**
     * 
     * @type {Uint8Array | File | buffer.File}
     * @memberof ProfileUpdatePhotoRequest
     */
    'File': Uint8Array | File | buffer.File;
}

