/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProfileAbout
 */
export interface ProfileAbout {
    /**
     * Text to display in your profile\'s About section The max length for the string is 139 characters.
     * @type {string}
     * @memberof ProfileAbout
     */
    'text': string;
}

