/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RemoveGroupParticipantRequestBody
 */
export interface RemoveGroupParticipantRequestBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoveGroupParticipantRequestBody
     */
    'wa_ids': Array<string>;
}

