/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RequestCodeAccount } from './request-code-account';

/**
 * 
 * @export
 * @interface RequestCodeResponse
 */
export interface RequestCodeResponse {
    /**
     * 
     * @type {Array<RequestCodeAccount>}
     * @memberof RequestCodeResponse
     */
    'account'?: Array<RequestCodeAccount>;
}

