/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RestoreSettingsRequestBody
 */
export interface RestoreSettingsRequestBody {
    /**
     * The data that was returned by the /v1/settings/backup API call
     * @type {string}
     * @memberof RestoreSettingsRequestBody
     */
    'data': string;
    /**
     * The password you used in the /v1/settings/backup API call to encrypt the backup data
     * @type {string}
     * @memberof RestoreSettingsRequestBody
     */
    'password': string;
}

