/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SetShardsRequestBody
 */
export interface SetShardsRequestBody {
    /**
     * 
     * @type {string}
     * @memberof SetShardsRequestBody
     */
    'cc': string;
    /**
     * 
     * @type {string}
     * @memberof SetShardsRequestBody
     */
    'phone_number': string;
    /**
     * 
     * @type {string}
     * @memberof SetShardsRequestBody
     */
    'pin': string;
    /**
     * 
     * @type {number}
     * @memberof SetShardsRequestBody
     */
    'shards': SetShardsRequestBodyShardsEnum;
}

type SetShardsRequestBodyShardsEnum = 1 | 2 | 4 | 8 | 16 | 32


