/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Standard Values: HOME, WORK
 * @export
 * @interface Url
 */
export interface Url {
    /**
     * Standard Values: HOME, WORK
     * @type {string}
     * @memberof Url
     */
    'type'?: string;
    /**
     * URL
     * @type {string}
     * @memberof Url
     */
    'url'?: string;
}

