/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Meta } from './meta';
import { Response } from './response';
import { UserResponseAllOf } from './user-response-all-of';
import { UserResponseItem } from './user-response-item';

/**
 * @type UserResponse
 * 
 * @export
 */
export type UserResponse = Response & UserResponseAllOf;


