/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserLoginResponseItem } from './user-login-response-item';

/**
 * 
 * @export
 * @interface UserLoginResponseAllOf
 */
export interface UserLoginResponseAllOf {
    /**
     * 
     * @type {Array<UserLoginResponseItem>}
     * @memberof UserLoginResponseAllOf
     */
    'users'?: Array<UserLoginResponseItem>;
}

