/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Meta } from './meta';
import { Response } from './response';
import { UserLoginResponseAllOf } from './user-login-response-all-of';
import { UserLoginResponseItem } from './user-login-response-item';

/**
 * @type UserLoginResponse
 * 
 * @export
 */
export type UserLoginResponse = Response & UserLoginResponseAllOf;


