/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserLoginResponseItem
 */
export interface UserLoginResponseItem {
    /**
     * Token expiration timestamp. By default, this is 7 days.
     * @type {string}
     * @memberof UserLoginResponseItem
     */
    'expires_after'?: string;
    /**
     * Authentication token to be used for all other WhatsApp Business API calls. The token must be sent in the authorization header in the format: Authorization: Bearer <authentication-token>
     * @type {string}
     * @memberof UserLoginResponseItem
     */
    'token'?: string;
}

