/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UserResponseItem } from './user-response-item';

/**
 * 
 * @export
 * @interface UserResponseAllOf
 */
export interface UserResponseAllOf {
    /**
     * 
     * @type {Array<UserResponseItem>}
     * @memberof UserResponseAllOf
     */
    'users'?: Array<UserResponseItem>;
}

