/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VideoById
 */
export interface VideoById {
    /**
     * 
     * @type {string}
     * @memberof VideoById
     */
    'caption': string;
    /**
     * 
     * @type {string}
     * @memberof VideoById
     */
    'id': string;
}

