/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Provider } from './provider';
import { VideoById } from './video-by-id';
import { VideoByProvider } from './video-by-provider';

/**
 * @type Video
 * The media object containing a video
 * @export
 */
export type Video = VideoById | VideoByProvider;


