/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookStatus
 */
export interface WebhookStatus {
    /**
     * 
     * @type {Array<Error>}
     * @memberof WebhookStatus
     */
    'errors'?: Array<Error>;
    /**
     * Message ID
     * @type {string}
     * @memberof WebhookStatus
     */
    'id'?: string;
    /**
     * WhatsApp ID of recipient
     * @type {string}
     * @memberof WebhookStatus
     */
    'recipient_id'?: string;
    /**
     * Status of message
     * @type {string}
     * @memberof WebhookStatus
     */
    'status'?: WebhookStatusStatusEnum;
    /**
     * Timestamp of the status message
     * @type {string}
     * @memberof WebhookStatus
     */
    'timestamp'?: string;
}

type WebhookStatusStatusEnum = 'sent' | 'delivered' | 'read' | 'failed' | 'deleted'


