/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookContactProfile } from './webhook-contact-profile';

/**
 * 
 * @export
 * @interface WebhookContact
 */
export interface WebhookContact {
    /**
     * 
     * @type {WebhookContactProfile}
     * @memberof WebhookContact
     */
    'profile'?: WebhookContactProfile;
    /**
     * The WhatsApp ID of the contact
     * @type {string}
     * @memberof WebhookContact
     */
    'wa_id'?: string;
}

