/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Webhooks
 */
export interface Webhooks {
    /**
     * Configures the maximum number of inflight callback requests that are sent out. Can be set to 6 (default), 12, 18, or 24.
     * @type {number}
     * @memberof Webhooks
     */
    'max_concurrent_requests'?: WebhooksMaxConcurrentRequestsEnum;
    /**
     * Inbound and outbound notifications are routed to this URL. A HTTPS-based endpoint is required; HTTP will not work.
     * @type {string}
     * @memberof Webhooks
     */
    'url'?: string;
}

type WebhooksMaxConcurrentRequestsEnum = 6 | 12 | 18 | 24


