/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhookContact } from './webhook-contact';
import { WebhookMessage } from './webhook-message';
import { WebhookStatus } from './webhook-status';

/**
 * 
 * @export
 * @interface WebhookEvent
 */
export interface WebhookEvent {
    /**
     * 
     * @type {Array<WebhookContact>}
     * @memberof WebhookEvent
     */
    'contacts'?: Array<WebhookContact>;
    /**
     * 
     * @type {Array<Error>}
     * @memberof WebhookEvent
     */
    'errors'?: Array<Error>;
    /**
     * 
     * @type {Array<WebhookMessage>}
     * @memberof WebhookEvent
     */
    'messages'?: Array<WebhookMessage>;
    /**
     * 
     * @type {Array<WebhookStatus>}
     * @memberof WebhookEvent
     */
    'statuses'?: Array<WebhookStatus>;
}

