/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookContactProfile
 */
export interface WebhookContactProfile {
    /**
     * Optional. As of v2.21.4, contains the sender\'s profile name.
     * @type {string}
     * @memberof WebhookContactProfile
     */
    'name'?: string;
}

