/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Contact } from './contact';
import { MessageContext } from './message-context';
import { MessageType } from './message-type';
import { WebhookAudio } from './webhook-audio';
import { WebhookDocument } from './webhook-document';
import { WebhookImage } from './webhook-image';
import { WebhookLocation } from './webhook-location';
import { WebhookSystem } from './webhook-system';
import { WebhookText } from './webhook-text';
import { WebhookVideo } from './webhook-video';
import { WebhookVoice } from './webhook-voice';

/**
 * 
 * @export
 * @interface WebhookMessage
 */
export interface WebhookMessage {
    /**
     * 
     * @type {WebhookAudio}
     * @memberof WebhookMessage
     */
    'audio'?: WebhookAudio;
    /**
     * 
     * @type {Array<Contact>}
     * @memberof WebhookMessage
     */
    'contacts'?: Array<Contact>;
    /**
     * 
     * @type {MessageContext}
     * @memberof WebhookMessage
     */
    'context'?: MessageContext;
    /**
     * 
     * @type {WebhookDocument}
     * @memberof WebhookMessage
     */
    'document'?: WebhookDocument;
    /**
     * 
     * @type {Array<Error>}
     * @memberof WebhookMessage
     */
    'errors'?: Array<Error>;
    /**
     * WhatsApp ID of the sender
     * @type {string}
     * @memberof WebhookMessage
     */
    'from'?: string;
    /**
     * Optional. WhatsApp group ID
     * @type {string}
     * @memberof WebhookMessage
     */
    'group_id'?: string;
    /**
     * Message ID
     * @type {string}
     * @memberof WebhookMessage
     */
    'id'?: string;
    /**
     * 
     * @type {WebhookImage}
     * @memberof WebhookMessage
     */
    'image'?: WebhookImage;
    /**
     * 
     * @type {WebhookLocation}
     * @memberof WebhookMessage
     */
    'location'?: WebhookLocation;
    /**
     * 
     * @type {WebhookSystem}
     * @memberof WebhookMessage
     */
    'system'?: WebhookSystem;
    /**
     * 
     * @type {WebhookText}
     * @memberof WebhookMessage
     */
    'text'?: WebhookText;
    /**
     * Message received timestamp
     * @type {string}
     * @memberof WebhookMessage
     */
    'timestamp'?: string;
    /**
     * type of the message
     * @type {MessageType}
     * @memberof WebhookMessage
     */
    'type'?: MessageType;
    /**
     * 
     * @type {WebhookVideo}
     * @memberof WebhookMessage
     */
    'video'?: WebhookVideo;
    /**
     * 
     * @type {WebhookVoice}
     * @memberof WebhookMessage
     */
    'voice'?: WebhookVoice;
}

