/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookLocation
 */
export interface WebhookLocation {
    /**
     * Address of the location
     * @type {string}
     * @memberof WebhookLocation
     */
    'address'?: string;
    /**
     * Latitude of location being sent
     * @type {number}
     * @memberof WebhookLocation
     */
    'latitude'?: number;
    /**
     * Longitude of location being sent
     * @type {number}
     * @memberof WebhookLocation
     */
    'longitude'?: number;
    /**
     * Name of the location
     * @type {string}
     * @memberof WebhookLocation
     */
    'name'?: string;
    /**
     * URL for the website where the user downloaded the location information
     * @type {string}
     * @memberof WebhookLocation
     */
    'url'?: string;
}

