/*
WhatsApp Business API

See https://developers.facebook.com/docs/whatsapp

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhookAudio
 */
export interface WebhookAudio {
    /**
     * Optional. Only present if specified.
     * @type {string}
     * @memberof WebhookAudio
     */
    'caption'?: string;
    /**
     * Absolute filename and location on media volume. This parameter is deprecated.
     * @type {string}
     * @memberof WebhookAudio
     * @deprecated
     */
    'file'?: string;
    /**
     * Filename on the sender\'s device. This will only be present in audio and document media messages.
     * @type {string}
     * @memberof WebhookAudio
     */
    'filename'?: string;
    /**
     * ID of the media. Can be used to delete the media if stored locally on the client.
     * @type {string}
     * @memberof WebhookAudio
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookAudio
     */
    'link'?: string;
    /**
     * Mime type of media
     * @type {string}
     * @memberof WebhookAudio
     */
    'mime_type'?: string;
    /**
     * Checksum
     * @type {string}
     * @memberof WebhookAudio
     */
    'sha256'?: string;
}

